
project_id = "bazbbweawubxqfebliil"

[functions.paystack]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.paystack-verify]
verify_jwt = true

[functions.send-payment-confirmation]
verify_jwt = true

[functions.ai-chatbot]
verify_jwt = false
