// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktqamfiqosqdzmgijute.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cWFtZmlxb3NxZHptZ2lqdXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODEyOTIsImV4cCI6MjA1OTE1NzI5Mn0.ewtLiuN3YU2hgRK-4CSJIKCd5XYKjZYkQeIy5dWWmmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);